### ISSUE TITLE
Getting "rid" of COCO

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_perception_libs#10]
This is a high priority and goes hand in hand with https://github.com/b-it-bots/mas_perception/issues/34 and https://github.com/b-it-bots/mas_tutorials/issues/7

We have enough objects of our own to thoroughly test our dataset generation and augmentation, and the resulting model

**Comment by alex-mitrevski** [comment]
I will close this since the major steps for training on our own data have been done in https://github.com/b-it-bots/dataset_interface, particularly with the most recent PR https://github.com/b-it-bots/dataset_interface/pull/3
