### ISSUE TITLE
Catkin build fails due to missing numpy/arrayobject.h

### ISSUE THREAD

**Issue by iswariyam** [b-it-bots/mas_perception_libs#17]
**use_numpy.hfatal error: numpy/arrayobject.h: No such file or directory fix in cmake list**

## Describe the bug
Error occurs despite the usage of python 2.7 and proper path setting for python 2.7

## Steps to Reproduce
1. Navigate to mas_perception_libs folder in the catkin workspace
2. Run catkin build --this

## Expected Behavior
Build should pass without any errors

## Environment

* Version used (branch/commit): kinetic

* PC:
    - developer's laptop
        * OS: Ubuntu 16.04
        * ROS version: ROS Kinetic
* build command:
    * catkin build

**Comment by iswariyam** [comment]
A simple work-around is to add the following in the CMakeLists.txt

`include_directories ("/usr/local/lib/python2.7/dist-packages/numpy/core/include")`

**Comment by minhnh** [comment]
This is an issue with `numpy` not generating correct symbolic link to the include directory. I will add an instruction to resolve this in `README.md`
