### ISSUE TITLE
Change back flexibility of cloud filter

### ISSUE THREAD

**Issue by mhwasil** [b-it-bots/mas_perception_libs#2]
* This new filter param makes us difficult to switch between fields (x,y,z).
* For example, now there is no passthrough filter available for z axis now.
* Every time this code is called, it will always do filter on (x,y), which is not always our interest. Eventually, this makes our robot slower.
```
        /* pass-through params */
        mPassThroughFilterX.setFilterFieldName("x");
        mPassThroughFilterX.setFilterLimits(pParams.mPassThroughLimitMinX, pParams.mPassThroughLimitMaxX);
        mPassThroughFilterY.setFilterFieldName("y");
        mPassThroughFilterY.setFilterLimits(pParams.mPassThroughLimitMinY, pParams.mPassThroughLimitMaxY);

        /* filter z-axis using voxel filter instead of making another member */
        mVoxelGridFilter.setFilterFieldName("z");
        mVoxelGridFilter.setFilterLimits(pParams.mVoxelLimitMinZ, pParams.mVoxelLimitMaxZ);

        /* voxel-grid params */
        mVoxelGridFilter.setLeafSize(pParams.mVoxelLeafSize, pParams.mVoxelLeafSize, pParams.mVoxelLeafSize);
```
* If it is the decision to keep, then we will probably need to maintain ours, just like it was in mcr_scene_segmentation.

**Comment by mhwasil** [comment]
I have commented on this during the pull request, but still it got merged.

**Comment by minhnh** [comment]
Please note that this is the last point of discussion:
https://github.com/b-it-bots/mas_perception/pull/32#discussion_r264211900

You did not say anything after my comment, so I assume it was agreed upon. Additionally, the [voxel filter can limit the point cloud along one dimension](http://docs.pointclouds.org/1.8.1/classpcl_1_1_voxel_grid.html#afc6d78962d7378aea245381fdb13e65e). This means that the feature you're asking for does not need the pass-though at all.

If you want to make it optional for the other dimensions, make a PR to change the constructor of `SacSceneSegmenter` to specify whether to skip the pass-through step or not.

In any case, I don't see the point of not enabling filtering clouds across all 3 dimensions. This simply gives more control over what goes into the following algorithms. If you argue for speed optimization, please include what's the difference with and without this step.

**Comment by mhwasil** [comment]
Without testing, we can already see it does double filters, which we dont need. Check the following result
Without <I just commented y filter on the code>
```
[RGB] pose array size: 3
Time: 1.47647
[RGB] pose array size: 3
Time: 1.41467
[RGB] pose array size: 3
Time: 1.44545

```
With double filter, which we dont need,
```
[RGB] pose array size: 3
Time: 1.9302
[RGB] pose array size: 3
Time: 1.85835
[RGB] Pose: 0.554472, -0.119411, 0.0226035
[RGB] pose array size: 3
Time: 1.68354
```

**Comment by mhwasil** [comment]
I have talked to @sthoduka about this, one solution is we can add options to disable passthroug x,y,z.

**Comment by minhnh** [comment]
Yes the best solution would be to have boolean flags to disable the filters as needed.
